### ISSUE TITLE
You kernel is not booting

### ISSUE THREAD

**Issue by rmnhg** [AdFad666/renaissance#1]
Hi AdFad666
I've built a boot.img with your kernel inside using LineageOS 14.1 sources from SonyLOS git account for Xperia E3.
The result was that phone does not power on, only blinking red light with that boot.img (tested with open device bootloader).
Have you tested your kernel on D2203? The problem perhaps is mine but I'm not sure.

**Comment by AdFad666** [comment]
It booted at the time of creation, which was over 4 months ago now. No idea why you wouldn't get it booting, but things move fast in LOS so the trees probably need updating.

I don't have time to look into this unfortunately.

**Comment by rmnhg** [comment]
Do you know what toolchain did you use?
